feasthub-backend/src/main/java/com/monsor/feasthub/ui/bean/EnumConstants.java
package com.monsor.feasthub.ui.bean;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

import com.monsor.feasthub.jpa.model.enums.AdditionalServiceOffering;
import com.monsor.feasthub.jpa.model.enums.AddressType;
import com.monsor.feasthub.jpa.model.enums.AuditTransactionType;
import com.monsor.feasthub.jpa.model.enums.BusinessStructure;
import com.monsor.feasthub.jpa.model.enums.BusinessTypes;
import com.monsor.feasthub.jpa.model.enums.ChequeStatus;
import com.monsor.feasthub.jpa.model.enums.DeliveryStatus;
import com.monsor.feasthub.jpa.model.enums.EventVisibility;
import com.monsor.feasthub.jpa.model.enums.FeastPointAccumulationType;
import com.monsor.feasthub.jpa.model.enums.FeesApplcability;
import com.monsor.feasthub.jpa.model.enums.FhAdditionalChargeFeesType;
import com.monsor.feasthub.jpa.model.enums.Gender;
import com.monsor.feasthub.jpa.model.enums.OrderPurchageModeType;
import com.monsor.feasthub.jpa.model.enums.OrderStatus;
import com.monsor.feasthub.jpa.model.enums.PaymentGateway;
import com.monsor.feasthub.jpa.model.enums.PaymentMode;
import com.monsor.feasthub.jpa.model.enums.PaymentStatus;
import com.monsor.feasthub.jpa.model.enums.ServiceOfferingTypes;
import com.monsor.feasthub.jpa.model.enums.TransactionMode;
import com.monsor.feasthub.jpa.model.enums.TransactionPurpose;
import com.monsor.feasthub.jpa.model.enums.UserSalutation;
import com.monsor.feasthub.jpa.model.enums.UserType;


@ManagedBean(name="EnumConstants")
@ApplicationScoped
public class EnumConstants {
	public AdditionalServiceOffering[] getAdditionalServiceOffering() {
		return AdditionalServiceOffering.values();
	}
	public AddressType[] getAddressType() {
		return AddressType.values();
	}
	public AuditTransactionType[] getAuditTransactionType() {
		return AuditTransactionType.values();
	}
	public BusinessStructure[] getBusinessStructure() {
		return BusinessStructure.values();
	}
	public BusinessTypes[] getBusinessTypes() {
		return BusinessTypes.values();
	}
	public ChequeStatus[] getChequeStatus() {
		return ChequeStatus.values();
	}
	public DeliveryStatus[] getDeliveryStatus() {
		return DeliveryStatus.values();
	}
	public EventVisibility[] getEventVisibility() {
		return EventVisibility.values();
	}
	public FeastPointAccumulationType[] getFeastPointAccumulationType() {
		return FeastPointAccumulationType.values();
	}
	public FeesApplcability[] getFeesApplcability() {
		return FeesApplcability.values();
	}
	public FhAdditionalChargeFeesType[] getFhAdditionalChargeFeesType() {
		return FhAdditionalChargeFeesType.values();
	}
	public Gender[] getGender() {
		return Gender.values();
	}
	public OrderPurchageModeType[] getOrderPurchageModeType() {
		return OrderPurchageModeType.values();
	}
	public OrderStatus[] getOrderStatus() {
		return OrderStatus.values();
	}
	public PaymentGateway[] getPaymentGateway() {
		return PaymentGateway.values();
	}
	public PaymentMode[] getPaymentMode() {
		return PaymentMode.values();
	}
	public PaymentStatus[] getPaymentStatus() {
		return PaymentStatus.values();
	}
	public ServiceOfferingTypes[] getServiceOfferingTypes() {
		return ServiceOfferingTypes.values();
	}
	public TransactionMode[] getTransactionMode() {
		return TransactionMode.values();
	}
	public TransactionPurpose[] getTransactionPurpose() {
		return TransactionPurpose.values();
	}
	public UserSalutation[] getUserSalutation() {
		return UserSalutation.values();
	}
	public UserType[] getUserType() {
		return UserType.values();
	}
}

feasthub-backend/src/main/java/com/monsor/feasthub/ui/controller/OrderController.java
package com.monsor.feasthub.ui.controller;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.stream.Collectors;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;

import com.monsor.feasthub.appservice.mobile.delivery.DeliverySlotAppService;
import com.monsor.feasthub.appservice.mobile.delivery.DeliverySlotsTimeAppService;
import com.monsor.feasthub.appservice.mobile.orderupdate.OrderTransactionAppService;
import com.monsor.feasthub.jpa.model.delivery.DeliverySlotsTime;
import com.monsor.feasthub.jpa.model.enums.OrderStatus;
import com.monsor.feasthub.jpa.model.order.OrderTransaction;

@ViewScoped
@ManagedBean
public class OrderController extends BaseController {

    /**
     * 
     */

    private int noOfPage = 0;

    private BigInteger orderId;

    private int recordPerPage = 10;
    
    private OrderTransaction viewOrder;

    private static final long serialVersionUID = 1L;

    private Date orderDate = new Date();

    private List<String> orderStatusIn = new ArrayList<String>();

    private List<OrderTransaction> recordPage;

    @ManagedProperty("#{orderTransactionAppService}")
    private OrderTransactionAppService orderTransactionAppService;
    
    @ManagedProperty("#{deliverySlotAppService}")
    private DeliverySlotAppService deliverySlotAppService;
    
    @ManagedProperty("#{deliverySlotsTimeAppService}")
    private DeliverySlotsTimeAppService deliverySlotsTimeAppService;


    public List<OrderStatus> listStatus() {
	return Arrays.asList(OrderStatus.values());
    }

    @PostConstruct
    public void init() {
	orderStatusIn.clear();
	orderStatusIn.add(OrderStatus.CONFIRMED_BY_COMPANY.toString());
	orderStatusIn.add(OrderStatus.BEING_PREPARED.toString());
	orderStatusIn.add(OrderStatus.OUT_FOR_DELIVERY.toString());
	orderStatusIn.add(OrderStatus.PACKING_IN_PROGRESS.toString());
	orderStatusIn.add(OrderStatus.DELIVERED.toString());
	orderStatusIn.add(OrderStatus.DELIVERED_TO_NEIGHBOUR.toString());
	orderStatusIn.add(OrderStatus.COMPLETED.toString());
    }

    public List<OrderTransaction> listOrders() {
	if (noOfPage == 0) {
	    searchOrder();
	}
	return recordPage;
    }

     
    private void searchOrder() {
	recordPage = orderTransactionAppService.listAllOrder(orderDate);
	recordPage = recordPage.stream()
		.filter(item -> orderStatusIn.contains(item.getOrderStatus().toString()))
		.collect(Collectors.toList());

    }
    
    public void initOrderInfo(){
	if(this.orderId !=null){
	  viewOrder =  orderTransactionAppService.findById(orderId);
	}
    }

    public void updateStatus(OrderTransaction order, OrderStatus orderStatus) {
	order.setOrderStatus(orderStatus);
	orderTransactionAppService.update(order);
    }

    public void performSearch() {

	searchOrder();
    }

    public Date getOrderDate() {
	return orderDate;
    }

    public void setOrderDate(Date orderDate) {
	this.orderDate = orderDate;
    }

    public OrderTransactionAppService getOrderTransactionAppService() {
	return orderTransactionAppService;
    }

    public void setOrderTransactionAppService(
	    OrderTransactionAppService orderTransactionAppService) {
	this.orderTransactionAppService = orderTransactionAppService;
    }

    public void nextPage() {

    }

    public int getNoOfPage() {
	return noOfPage;
    }

    public void setNoOfPage(int noOfPage) {
	this.noOfPage = noOfPage;
    }

    public int getRecordPerPage() {
	return recordPerPage;
    }

    public void setRecordPerPage(int recordPerPage) {
	this.recordPerPage = recordPerPage;
    }

    public List<OrderTransaction> getRecordPage() {
	return recordPage;
    }

    public void setRecordPage(List<OrderTransaction> recordPage) {
	this.recordPage = recordPage;
    }

    public BigInteger getOrderId() {
	return orderId;
    }

    public void setOrderId(BigInteger orderId) {
	this.orderId = orderId;
    }

    public List<String> getOrderStatusIn() {
	return orderStatusIn;
    }

    public void setOrderStatusIn(List<String> orderStatusIn) {
	this.orderStatusIn = orderStatusIn;
    }

    public OrderTransaction getViewOrder() {
        return viewOrder;
    }

    public void setViewOrder(OrderTransaction viewOrder) {
        this.viewOrder = viewOrder;
    }

    public DeliverySlotAppService getDeliverySlotAppService() {
        return deliverySlotAppService;
    }

    public void setDeliverySlotAppService(DeliverySlotAppService deliverySlotAppService) {
        this.deliverySlotAppService = deliverySlotAppService;
    }

    public DeliverySlotsTimeAppService getDeliverySlotsTimeAppService() {
        return deliverySlotsTimeAppService;
    }

    public void setDeliverySlotsTimeAppService(
    	DeliverySlotsTimeAppService deliverySlotsTimeAppService) {
        this.deliverySlotsTimeAppService = deliverySlotsTimeAppService;
    }
    
    public String getDeliverySlot(BigInteger id){
	return deliverySlotAppService.findById(id).getPartOfDay();
    }
    
    public String getDeliverySlotsTime(BigInteger id){
   	DeliverySlotsTime time = deliverySlotsTimeAppService.findById(id);
   	return String.format("%s - %s", time.getSlotsTimingStartsAt(),time.getSlotsTimingEndsAt());
       }
}

feasthub-backend/src/main/webapp/order/listOrders.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<!-- 
		Replace path to template, title, header and body
		with actual data.
	 -->
<ui:composition template="/templates/common.xhtml">
	<ui:define name="pageTitle">Title</ui:define>
	<ui:define name="pageHeader">Header</ui:define>
	<ui:define name="body">
		<form jsfc="h:form" id="Form">
			<div class="Card ShadowEffect ">
				<div class="Container100 Responsive100">
					<div class="ContainerIndent">
						<h2 class="BigTopic">Search Panel</h2>
						<div class="ui-fluid">
							<p:panelGrid columns="6" style="width:100%"
								columnClasses="ui-grid-col-2,ui-grid-col-10,ui-grid-col-2,ui-grid-col-10,ui-grid-col-2,ui-grid-col-10"
								styleClass="ui-panelgrid-blank">
								<p:outputLabel value="Date" />
								<p:calendar value="#{orderController.orderDate}"
									pattern="dd-MM-yyyy">
									<p:ajax update="@this" event="dateSelect" />
								</p:calendar>
								<p:outputLabel for="orderStatus" value="Order Status" />

								<p:selectCheckboxMenu id="orderStatus"
									value="#{orderController.orderStatusIn}" label="Order Statuses"
									filter="true" filterMatchMode="startsWith"
									panelStyle="width:250px">
									<f:selectItems value="#{orderController.listStatus()}"
										var="item" itemValue="#{item.name()}"
										itemLabel="#{item.value}" />
									<p:ajax update="@this" event="change" />
								</p:selectCheckboxMenu>
							</p:panelGrid>


							<p:outputPanel autoUpdate="true">
								<div style="float: right">
									<p:commandButton value="Search" icon="fa fa-search"
										update="orders" process="@this"
										action="#{orderController.performSearch}"></p:commandButton>
								</div>
							</p:outputPanel>

						</div>
					</div>
				</div>
			</div>
			<br />
			<p:dataTable filterDelay="1" id="orders" var="order"
				widgetVar="orders" value="#{orderController.recordPage}"
				rowKey="#{order.id}" emptyMessage="#{msg.nodatafound}">
				<f:facet name="header">
					<div class="datatable-header-left">
						<h:outputText value="Orders" style="font-weight:bold" />

					</div>
					<div class="datatable-header-right">
						<h:outputText value="Search all fields:"  style="font-weight:bold" />
						<p:inputText id="globalFilter" onkeyup="PF('orders').filter()"
							style="width:150px" placeholder="Enter keyword" />
						<p:spacer height="20" width="1"></p:spacer>
					</div>
					<br />
				</f:facet>
				<p:column headerText="Order Id" sortBy="#{order.orderId}"
					filterStyle="display:none" filterBy="#{order.orderId}"
					filterMatchMode="contains">
					<a href="#{request.contextPath}/vieworder/#{order.id}" >#{order.orderId}</a>
					
				</p:column>
				<p:column headerText="Purchage Mode"
					sortBy="#{order.paymentMode.value}" filterStyle="display:none"
					filterBy="#{order.paymentMode.value}" filterMatchMode="contains">
					<h:outputText value="#{order.paymentMode.value}" />
				</p:column>
				<p:column headerText="Order Amount">
					<h:outputText value="#{order.totalAmount}" />
				</p:column>
				<p:column headerText="Order Status" filterStyle="display:none"
					sortBy="#{order.orderStatus.value}"
					filterBy="#{order.orderStatus.value}" filterMatchMode="contains">

					<h:outputText value="#{order.orderStatus.value}" />
				</p:column>
				<p:column headerText="Action">
					<p:commandButton value="Being Prepared" update="orders"
						process="@this" icon="fa fa-mail-forward"
						rendered="#{order.orderStatus == 'CONFIRMED_BY_COMPANY'}"
						action="#{orderController.updateStatus(order, 'BEING_PREPARED')}" />
					<p:commandButton value="Packing In Progress" update="orders"
						process="@this" icon="fa fa-mail-forward"
						rendered="#{order.orderStatus == 'BEING_PREPARED'}"
						action="#{orderController.updateStatus(order, 'PACKING_IN_PROGRESS')}" />
					<p:commandButton value="Out For Delivery" update="orders"
						process="@this"
						rendered="#{order.orderStatus == 'PACKING_IN_PROGRESS'}"
						icon="fa fa-mail-forward"
						action="#{orderController.updateStatus(order, 'OUT_FOR_DELIVERY')}" />
					<p:commandButton value="Delivered" update="orders" process="@this"
						rendered="#{order.orderStatus == 'OUT_FOR_DELIVERY'}"
						icon="fa fa-mail-forward"
						action="#{orderController.updateStatus(order, 'DELIVERED')}" />
					<p:commandButton value="Delivered To Neighbour" update="orders"
						process="@this"
						rendered="#{order.orderStatus == 'OUT_FOR_DELIVERY'}"
						icon="fa fa-mail-forward"
						action="#{orderController.updateStatus(order, 'DELIVERED_TO_NEIGHBOUR')}" />
					<p:commandButton value="Completed" update="orders" process="@this"
						rendered="#{order.orderStatus == 'DELIVERED' or order.orderStatus == 'DELIVERED_TO_NEIGHBOUR'}"
						icon="fa fa-mail-forward"
						action="#{orderController.updateStatus(order, 'COMPLETED')}" />
					<h:outputText value="Completed"
						rendered="#{order.orderStatus == 'COMPLETED'}" />

				</p:column>

			</p:dataTable>
		</form>
	</ui:define>
</ui:composition>

</html>

feasthub-backend/src/main/webapp/order/orderInfo.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui">

<!-- 
		Replace path to template, title, header and body
		with actual data.
	 -->
<ui:composition template="/templates/common.xhtml">
	<ui:define name="pageTitle">Title</ui:define>
	<ui:define name="pageHeader">Header</ui:define>
	<ui:define name="body">
		<form jsfc="h:form" id="Form">

			<div class="Container100">
				<div class="Container100 Responsive100">
					<div class="Container40 Responsive50">
						<div class="ContainerIndent" >
							<div class="Card ShadowEffect HeiAutoOnMobile" style="height:200px !important">
								<h2 class="CardTopic">
									<i class="fa fa-info Fs25 Fleft MarRight10"></i> ORDER INFO

								</h2>
								<div class="SeparatorFull"></div>
								<p:panelGrid columns="2" style="width:100%"
									columnClasses="ui-grid-col-2,ui-grid-col-10"
									styleClass="ui-panelgrid-blank">
									<p:outputLabel value="Order Id" />
									<h:outputText value="#{orderController.viewOrder.orderId}" />

									<p:outputLabel value="Order Status" />
									<h:outputText
										value="#{orderController.viewOrder.orderStatus.value}" />

									<p:outputLabel value="Payment Status" />
									<h:outputText
										value="#{orderController.viewOrder.paymentStatus.value}" />

									<p:outputLabel value="Payment Mode" />
									<h:outputText
										value="#{orderController.viewOrder.paymentMode.value}" />

									<p:outputLabel value="Order Created on" />
									<h:outputText value="#{orderController.viewOrder.orderDate}">
										<f:convertDateTime pattern="dd-MM-yyyy" timeZone="IST" />
									</h:outputText>

								</p:panelGrid>
							</div>
						</div>
					</div>


					<div class="Container30 Responsive30">
						<div class="Container100 Responsive50">
							<div class="ContainerIndent">
								<div class="Card ShadowEffect HeiAutoOnMobile" style="height:200px !important">
									<h2 class="CardTopic">
										<i class="fa fa-street-view Fs25 Fleft MarRight10"></i>
										DELIVERY DETAILS

									</h2>
									<div class="SeparatorFull"></div>

									<div class="Wid100">
										<div class="ContainerIndent Fs16 BoldGray">
											<p:outputLabel
												value="Address (#{orderController.viewOrder.deliveryAddressId.addressType.value})" />
											<br /> <span class="Gray Fs14">#{orderController.viewOrder.deliveryAddressId.name}<br />
												#{orderController.viewOrder.deliveryAddressId.address},
												#{orderController.viewOrder.deliveryAddressId.landmark},<br />
												#{orderController.viewOrder.deliveryAddressId.city},
												#{orderController.viewOrder.deliveryAddressId.stateCode},
												#{orderController.viewOrder.deliveryAddressId.pincode}
											</span>
										</div>


									</div>

								</div>
							</div>
						</div>
					</div>
					<div class="Container30 Responsive30" >
						<div class="Container100 Responsive50" >
							<div class="ContainerIndent" >
								<div class="Card ShadowEffect HeiAutoOnMobile" style="height:200px !important">
									<h2 class="CardTopic">
										<i class="fa fa-street-view Fs25 Fleft MarRight10"></i> ORDER
										PROCESSING

									</h2>
									<div class="SeparatorFull"></div>

									<center>
										<p:commandButton value="Being Prepared" update="@form"
											process="@this" icon="fa fa-mail-forward"
											rendered="#{orderController.viewOrder.orderStatus == 'CONFIRMED_BY_COMPANY'}"
											action="#{orderController.updateStatus(orderController.viewOrder, 'BEING_PREPARED')}" />
										<p:commandButton value="Packing In Progress" update="@form"
											process="@this" icon="fa fa-mail-forward"
											rendered="#{orderController.viewOrder.orderStatus == 'BEING_PREPARED'}"
											action="#{orderController.updateStatus(orderController.viewOrder, 'PACKING_IN_PROGRESS')}" />
										<p:commandButton value="Out For Delivery" update="@form"
											process="@this"
											rendered="#{orderController.viewOrder.orderStatus == 'PACKING_IN_PROGRESS'}"
											icon="fa fa-mail-forward"
											action="#{orderController.updateStatus(orderController.viewOrder, 'OUT_FOR_DELIVERY')}" />
										<p:commandButton value="Delivered" update="@form"
											process="@this"
											rendered="#{orderController.viewOrder.orderStatus == 'OUT_FOR_DELIVERY'}"
											icon="fa fa-mail-forward"
											action="#{orderController.updateStatus(orderController.viewOrder, 'DELIVERED')}" />
										<p:commandButton value="Delivered To Neighbour"
											update="@form" process="@this"
											rendered="#{orderController.viewOrder.orderStatus == 'OUT_FOR_DELIVERY'}"
											icon="fa fa-mail-forward"
											action="#{orderController.updateStatus(orderController.viewOrder, 'DELIVERED_TO_NEIGHBOUR')}" />
										<p:commandButton value="Completed" update="@form"
											process="@this"
											rendered="#{orderController.viewOrder.orderStatus == 'DELIVERED' or orderController.viewOrder.orderStatus == 'DELIVERED_TO_NEIGHBOUR'}"
											icon="fa fa-mail-forward"
											action="#{orderController.updateStatus(orderController.viewOrder, 'COMPLETED')}" />
										<h:outputText value="Completed"
											rendered="#{orderController.viewOrder.orderStatus == 'COMPLETED'}" />

									</center>

								</div>
							</div>
						</div>
					</div>

				</div>
				<div class="Container100 Responsive100">
					<div class="ContainerIndent">
						<div class="Card ShadowEffect HeiAutoOnMobile">
							<h2 class="CardTopic">
								<i class="fa fa-list-ul Fs25 Fleft MarRight10"></i> ORDER ITEMS

							</h2>
							<div class="SeparatorFull"></div>
							<div style="background-color: #ABDD83">
								<p:panelGrid columns="7" style="width:100%"
									columnClasses="ui-grid-col-250,ui-grid-col-10,ui-grid-col-10,ui-grid-col-50,ui-grid-col-50,ui-grid-col-50,ui-grid-col-50"
									styleClass="ui-panelgrid-blank">
									<h:outputFormat value="Item Details" />
									<h:outputFormat value="" />
									<h:outputFormat value="" />
									<h:outputFormat value="Quantity" style="float:right" />
									<h:outputFormat value="Price" style="float:right" />
									<h:outputFormat value="Taxes" style="float:right" />
									<h:outputFormat value="Final Price" style="float:right" />
								</p:panelGrid>
							</div>
							<p:dataGrid value="#{orderController.viewOrder.orderEvents}"
								var="event" columns="1" styleClass="ui-panelgrid-blank"
								rowIndexVar="vs">
								<p:outputLabel
									value="#{vs+1}. #{event.eventDetails.eventCuisine.foodMenuItem.foodName}"
									style="font-weight:bold !important" />
								<div class="SeparatorHalf"></div>
								<p:panelGrid columns="7" style="width:100%;align:right"
									columnClasses="ui-grid-col-10,ui-grid-col-10,ui-grid-col-10,ui-grid-col-50,ui-grid-col-50,ui-grid-col-50,ui-grid-col-50"
									styleClass="ui-panelgrid-blank">
									<img
										src="#{event.eventDetails.eventCuisine.foodMenuItem.image1Url}"
										alt="#{event.eventDetails.eventCuisine.foodMenuItem.foodName}"
										height="100" width="150" />
									<h:outputText
										value="#{event.eventDetails.eventCuisine.foodMenuItem.foodShortDescription}" />
									<h:outputText
										value="#{event.eventDetails.eventCuisine.foodMenuItem.foodLongDescription}" />
									<h:outputText value="#{event.orderedQuantity}"
										style="float:right" />
									<h:outputText value="#{event.eventDetails.offeredPrice}"
										style="float:right">
										<f:convertNumber currencySymbol="₹" type="currency" />
									</h:outputText>
									<h:outputText value="#{event.eventDetails.addTaxes}"
										style="float:right">
										<f:convertNumber currencySymbol="₹" type="currency" />
									</h:outputText>
									<h:outputText
										value="#{event.eventDetails.finalOfferedPrice * event.orderedQuantity}"
										style="float:right">
										<f:convertNumber currencySymbol="₹" type="currency" />
									</h:outputText>


								</p:panelGrid>
								<f:facet name="footer">
									<div class="Container30 Responsive30">
										<div class="ContainerIndent">
											<h:panelGrid columns="3"
												columnClasses="right-align,right-align,right-align"
												style="width:300px !important">
												<h:outputText value="Total Amount" style="float:right" />
												<h:outputText value=":" />
												<h:outputText
													value="#{orderController.viewOrder.totalAmount-orderController.viewOrder.totalTax}"
													style="float:right">
													<f:convertNumber currencySymbol="₹" type="currency" />
												</h:outputText>
												<h:outputText value="Total Taxes" style="float:right" />
												<h:outputText value=":" />
												<h:outputText value="#{orderController.viewOrder.totalTax}"
													style="float:right">
													<f:convertNumber currencySymbol="₹" type="currency" />
												</h:outputText>
												<h:outputText value="Total Amount (Including Taxes)"
													style="float:right" />
												<h:outputText value=":" />
												<h:outputText
													value="#{orderController.viewOrder.totalAmount}"
													style="float:right">
													<f:convertNumber currencySymbol="₹" type="currency" />
												</h:outputText>

											</h:panelGrid>
										</div>
									</div>
								</f:facet>
							</p:dataGrid>
						</div>
					</div>
				</div>
				<div class="Container100 Responsive100">
					<div class="ContainerIndent">
						<div class="Card ShadowEffect HeiAutoOnMobile">
							<h2 class="CardTopic">
								<i class="icon icon-schedule2 Fs25 Fleft MarRight10"></i>
								DELIVERY SCHEDULE
							</h2>
							<div class="SeparatorFull"></div>
							<p:scrollPanel mode="native" style="height:200px">
								<p:dataGrid value="#{orderController.viewOrder.orderDelivery}"
									columns="#{orderController.viewOrder.orderDelivery.size()}"
									var="del">
									<p:outputPanel rendered="#{currentDate gt del.deliveryDate}">
										<div class="Container40"
											style="width: 300px !important; margin: 10px 10px 10px 10px; padding: 10px; border: 1px solid rgb(216, 215, 215) !important">
											<div class="SoftGreenBack DispInlBlock Fleft"
												style="margin: 1px 10px 1px 1px !important; padding: 20px 10px;">
												<i class="fa fa-bell-slash Green Fs100"></i>
											</div>
											<p>
												<span class="Gray FontRobotoLight "><h:outputText
														value="#{del.deliveryDate}">
														<f:convertDateTime pattern="dd-MM-yyyy" timeZone="IST" />
													</h:outputText></span><br /> <span class="Gray FontRobotoLight "><h:outputText
														value="#{orderController.getDeliverySlot(del.deliverySlotsId)}">

													</h:outputText></span><br /> <span class="Orange  FontRobotoBold"><h:outputText
														value="#{orderController.getDeliverySlotsTime(del.deliverySlotsTimeId)}">

													</h:outputText></span><br /> <span class="Orange  FontRobotoBold"><h:outputText
														value="#{del.deliveryStatus.value}" /></span><br /> <span
													class="Orange  FontRobotoBold"><h:outputText
														value="#{del.deliveryBy}" /></span>
											</p>
										</div>
									</p:outputPanel>
									<p:outputPanel rendered="#{currentDate le del.deliveryDate}">
										<div class="Container40"
											style="width: 250px !important; margin: 10px 10px 10px 10px; padding: 10px; border: 1px solid rgb(216, 215, 215) !important">
											<div class="SoftOrangeBack DispInlBlock Fleft"
												style="margin: 1px 10px 1px 1px !important; padding: 20px 10px;">
												<i class="fa fa-bell Orange Fs100"></i>
											</div>
											<p>
												<span class="Gray FontRobotoLight "><h:outputText
														value="#{del.deliveryDate}">
														<f:convertDateTime pattern="dd-MM-yyyy" timeZone="IST" />
													</h:outputText></span><br /> <span class="Gray FontRobotoLight "><h:outputText
														value="#{orderController.getDeliverySlot(del.deliverySlotsId)}">

													</h:outputText></span><br /> <span class="Orange  FontRobotoBold"><h:outputText
														value="#{orderController.getDeliverySlotsTime(del.deliverySlotsTimeId)}">

													</h:outputText></span><br /> <span class="Orange  FontRobotoBold"><h:outputText
														value="#{del.deliveryStatus.value}" /></span><br /> <span
													class="Orange  FontRobotoBold"><h:outputText
														value="#{del.deliveryBy}" /></span>
											</p>
										</div>
									</p:outputPanel>
								</p:dataGrid>
							</p:scrollPanel>
						</div>

					</div>
				</div>

			</div>

		</form>
	</ui:define>
</ui:composition>

</html>